# Labels
TITLE_LABEL = 'CSV file splitter'
OUTPUT_FOLDER_BUTTON_LABEL = 'Select output folder...'
NUMBER_OF_CHUNKS_LABEL = 'Insert number of chunks'
NUMBER_OF_CHUNKS_ENTRY_DEFAULT_VALUE = 2
CSV_FILE_SELECTION_BUTTON_LABEL = 'Select input CSV file...'
CSV_FILE_SPLITTER_BUTTON_LABEL = 'Split CSV file...'
QUIT_BUTTON_LABEL = 'Quit...'

# Elements coordinates
TITLE_LABEL_COORDINATES = (0,0)
NUMBER_OF_CHUNKS_LABEL_COORDINATES = (1,0)
NUMBER_OF_CHUNKS_ENTRY_COORDINATES = (1,1)
QUIT_BUTTON_COORDINATES = (5,0)
OUTPUT_FOLDER_BUTTON_COORDINATES = (3,0)
OUTPUT_FOLDER_LABEL_COORDINATES = (3,1)
CSV_FILE_SELECTION_BUTTON_COORDINATES = (2,0)
CSV_FILE_SELECTION_LABEL_COORDINATES = (2,1)
CSV_FILE_SPLITTER_BUTTON_COORDINATES = (4,0)